### ISSUE TITLE
consider writing nlcg.json with indent=2

### ISSUE THREAD

**Issue by ltalirz** [simonpintarelli/nlcglib#8]
Currently, the nlcg.json files are written on a single line which makes them hard to read.

I understand that these are meant for post-processing - still, it might be worth considering printing them with what would be equivalent to `indent=2` in the python [json module](https://docs.python.org/3/library/json.html#json.dump), as this makes it much easier for users browsing them with a text editor on the HPC machine.

**Comment by simonpintarelli** [comment]
I was assuming that `jq` (https://stedolan.github.io/jq/) is available on most systems. The unformatted json consumes approx 2x less disk space. The file is mainly for debugging purposes and an end user won't be interested in it usually. Aiida might use it instead of parsing the stdout to monitor convergence speed, for example.

The file is of the following form (this is a hack to preserve the output in case of unexpected termination, walltime limit for example):
```
{nlcg_data_iteration0}
...
{nlcg_data_iterationN}
```

It can be converted to a valid json file using `jq --slurp nlcg.json`. And, for example, `jq -s nlcg.json | jq .[5]` can be used to show the data of the 5-th nlcg iteration. Every 10th iteration the band energies / occupancies are dumped, this might be a huge chunk of data, and therefore, the best is to query it's contents using the `jq` command and not opening it in an editor.

**Comment by ltalirz** [comment]
I see, no worries - was just a suggestion.
Indeed I guess `jq` is present on many systems.

> The file is of the following form (this is a hack to preserve the output in case of unexpected termination, walltime limit for example):

I see. It seems to me that this file is valid JSON Lines format https://jsonlines.org/
You might want to change the extension to `.jsonl`.

**Comment by simonpintarelli** [comment]
Thank you! I wasn't aware of the JSON lines format, I'll change the extension accordingly.
