### ISSUE TITLE
Slope error

### ISSUE THREAD

**Issue by ltalirz** [simonpintarelli/nlcglib#9]
I've encountered the following error that led to a crash of the sirius-enabled QE executable (MPI abort):

```
0              -958.6926595887137       6.3084519655470e+01 -1.0000000000000e+00
         kT * S       : -0.0000535106230
         Fermi energy : 0.9024692993010
         KS energy    : -958.6926060780906
atom              moment                |moment|
--------------------------------------------------------------------------------
   0  [  0.0000,   0.0000,   1.1120]    1.111982
   1  [  0.0000,   0.0000,   0.0413]    0.041284
   2  [  0.0000,   0.0000,   0.0021]    0.002077
   3  [  0.0000,   0.0000,  -0.0092]    0.009159
   4  [  0.0000,   0.0000,  -0.0125]    0.012538
   5  [  0.0000,   0.0000,  -0.0183]    0.018315

SIRIUS: exception
Slope error
SIRIUS: exception
Slope error
```

The `nlcg.out` contains (after a block or `NUL`s https://github.com/simonpintarelli/nlcglib/issues/7)
```
WARNING: No descent direction found, nlcg didn't reach final tolerance
```

Is this expected?
What can be the reason for this?

**Comment by simonpintarelli** [comment]
When using ultrasoft or PAW pseudopotentials, the density can attain negative values. If this happens a warning is printed to the stdout and the density is set to zero at the points where it was negative. This is because libxc does not accept negative values for the density.

The SCF might recover from this, e.g. it might happen only in the first few iterations. NLCG will fail in general, because H(rho(psi)) * psi is no longer the gradient of the total energy wrt to the plane wave coefficients of the wave functions. And consequently the direction, in which the line search (of the nonlinear CG iteration) is performed, might not be a descent direction anymore. This is a deficit of the discretization (plane waves) and can't be fixed by the implementation unfortunately. 

In case there is no warning about a negative density, it might be a problem with the cold/methfessel-paxton smearing, this is a recent addition and not yet extensively tested.

**Comment by ltalirz** [comment]
> In case there is no warning about a negative density

This is a vc-relax calculation, and there were occasional warnings about negative charge densities in earlier ionic steps but those apparently did not cause this error.

See full output [here](https://1drv.ms/u/s!AuW5cOyKLNS4hFbaL09g89KP3WUF?e=A1gd0F).

How would one know as a user what caused this error?

> In case there is no warning about a negative density, it might be a problem with the cold/methfessel-paxton smearing, this is a recent addition and not yet extensively tested.

Perhaps that is the more likely explanation?
Are you saying I should be using Gaussian smearing with sirius for the moment?
